@karolinska_click_buttons
 Feature: 
  Gå till startsidan

 @karolinska_click_buttons
 Scenario: Klicka på "Stöd och verktyg"
  Given I go to "https://medarbetare.ki.se/"
  Then I should see "Stöd och verktyg"
  And I click on the element with xpath "//a[contains(text(),'Stöd och verktyg')]"
  And I should see "Arkiv och registratur"
  And I should see "Inköp och upphandling"
  And I should see "Föreskrifter, riktlinjer och anvisningar"
  And I should see "Arrangera konferenser och evenemang"
  And I should see "IT och telefoni"
  And I should see "Resa i tjänsten"
  And I should see "Ekonomi"
  And I should see "Kommunikationsstöd"
  And I should see "Miljö och Säkerhet"
  And I should see "HR-stöd"
  And I should see "Laboratoriesäkerhet"
  And I should see "Projektprocessen - AU-projekt"
  And I should see "Vad behöver du i din yrkesroll"
  And I should see "Forskarstöd"
  And I should see "För dig som forskar"
  And I should see "Grants Office - stöd för forskare"
  And I should see "Forskningsstöd för pågående EU-, US- och Sida-projekt"
  And I should see "Laboratoriesäkerhet"
  And I should see "Innovationsstöd"
  And I should see "Som är chef och ledare"
  And I should see "Arbetsmiljöansvar"
  And I should see "Chef- och ledarskapsutveckling"
  And I should see "Ledarskapsutbildningar"
  And I should see "Omställning"
  And I should see "Rekrytera"
  And I should see "System som underlättar administration"
  And I should see "Information om administrativa stödsystem"
