@karolinska 
 Feature: 
  Gå till startsidan

 @karolinska
 Scenario: Gå till huvudsidan
  Given I go to "https://medarbetare.ki.se/"
  Then I should see "Din anställning"
  And I should see "Site in English"
  And I should see "Genvägar"
  And I should see "Stöd och verktyg"
  And I should see "Utbilda och forska"
  And I should see "På plats på campus"
  And I should see "Vårt KI"
  And I should see "Digitala verktyg"
  And I should see "Lokal webb"
  And I should see "Jag vill"
  And I should see "Byta lösenord på mitt KI-konto"
  And I should see "Redigera min profilsida"
  And I should see "Rapportera en incident"
  And I should see "Boka en lokal"
  And I should see "Läsa min e-post på webben"
  And I should see "Godkänna en faktura"
  And I should see "Hantera och dokumentera forskningsdata"
  And I should see "Dagens lunch på campus Flemingsberg"
  And I should see "Alfreds restaurang och café"
  And I should see "Allé Elva Kök & Matsal"
  And I should see "Bistro A"
  And I should see "Café Arom"
  And I should see "Flemingsbergs Stories Zanderska Huset"
  And I should see "Restaurang 61:an"
  And I should see "Restaurang Tango"
  And I should see "Stockholm Food"
  And I should see "Dagens lunch på campus Solna"
  And I should see "Restaurang Nanna Svartz"
  And I should see "Café Erik Jorpes"
  And I should see "Fakultetsklubben Svarta Räfven"
  And I should see "Haga gatukök"
  And I should see "Mollan Asian Kök"
  And I should see "Restaurang Hjulet"
  And I should see "Restaurang Jöns Jacob"
  And I should see "STHLM Street Lunch"
  And I should see "Dagens lunch i Karolinska Universitetssjukhuset Solna"
  And I should see "Astrid Stories"
  And I should see "Den Glada Restaurangen (CMM)"
  And I should see "Livet [restaurant]"
  And I should see "Vete-katten"
  And I should see "Kalender"